robot_name: "robile"
layout:
  - # ![DO NOT REMOVE THIS LINE] these are the brick at ground level
    - ["active_wheel", "active_wheel"]
    - ["cpu", "battery"]
    - ["active_wheel", "active_wheel"]
  - # add other level of brick to your robot
    - ["skip", "skip"]
    - ["skip", "skip"]
    - ["battery", "battery"]
